version: '3'

services:

  memas-init:
    build: 
      context: .
    image: memas:latest
    container_name: memas-init
    depends_on: 
      scylla:
        condition: service_healthy
      milvus:
        condition: service_started
      es01:
        condition: service_started
    env_file:
      - .env
    volumes:
      - memas_data:/memas
    command: /memas/init.sh 30
    profiles: ["dev"]

  memas:
    build: 
      context: .
    image: memas:latest
    container_name: memas
    depends_on: 
      memas-init:
        condition: service_completed_successfully
    env_file:
      - .env
    volumes:
      - memas_data:/memas
    ports:
      - 8010:8010
    # command: ./wait-for-it.sh milvus-standalone:19530 -t 300 -- gunicorn -w 1 -k eventlet 'memas.app:create_app(config_filename="memas-config.yml")'
    profiles: ["dev"]

  scylla:
    image: scylladb/scylla
    container_name: scylla
    command: --smp=2
    ports:
      - 9042:9042
    volumes:
      - scylla_data:/var/lib/scylla
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 10s
      timeout: 5s
      retries: 10

  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - etcd_data:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2022-03-17T06-34-49Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - minio_data:/data
    command: minio server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  milvus:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.2.8
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - milvus_data:/var/lib/milvus
    ports:
      - 19530:19530
      - 9091:9091
    depends_on:
      - "etcd"
      - "minio"

  es01:
    container_name: memas-es01
    image: elasticsearch:${ES_VERSION}
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - ${ES_PORT}:9200
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - discovery.type=single-node
      - xpack.security.enabled=false
    mem_limit: ${MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1


volumes:
  memas_data:
    driver: local

  esdata01:
    driver: local

  etcd_data:
    driver: local

  minio_data:
    driver: local

  milvus_data:
    driver: local
  
  scylla_data:
    driver: local

networks:
  default:
    name: memas_dev
