CASSANDRA:
  ip: "scylla"
  port: 9042
  keyspace: "memas"
  replication_factor: 1

ELASTICSEARCH:
  ip: "memas-es01"
  port: 9200

MILVUS:
  ip: "milvus-standalone"
  port: 19530

CELERY:
  broker_url: "redis://redis"
  result_backend: "redis://redis"
  task_ignore_result: True
