CASSANDRA:
  ip: "127.0.0.1"
  port: 9042
  keyspace: "memas_integ_test"
  replication_factor: 1

ELASTICSEARCH:
  ip: "127.0.0.1"
  port: 9200

MILVUS:
  ip: "127.0.0.1"
  port: 19530

CELERY:
  broker_url: "redis://localhost"
  result_backend: "redis://localhost"
  task_ignore_result: True
